version: '3.5'

services:

  db:
   image: postgres
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: example
   ports:
     - 5432:5432

  adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080

  nest:
   build: .
   volumes:
     - .:/nest
   ports:
     - 5000:5000
   tty: true
